Add the voltage level id of equipment in ElasticSearch
gridsuite/study-server pull request #125
Opened 2021-10-18 11:08 UTC by SlimaneAmar

Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>

2021-10-20 11:10 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/study/server/elasticsearch/EquipmentInfosServiceImpl.java
> +                infos.stream().filter(e -> EquipmentType.isSwitchType(e.getType())).sorted(Comparator.comparing(EquipmentInfos::getId))
Maybe splitting first the 'infos' stream into a Map<EquipmentType, List<EquipmentInfos>> with Collectors.groupingBy(EquipmentInfos::getType)
and the sort each List in the map
would be more efficient ?

2021-10-21 07:27 UTC, FranckLecuyer approved these changes

2021-10-21 08:29 UTC, niconoir requested changes

2021-10-21 08:29 UTC, niconoir commented on src/main/java/org/gridsuite/study/server/elasticsearch/EquipmentInfosServiceImpl.java
> +            .collect(Collectors.toList());
This part of code seems to return a list sorted by equipment id, but not by equipment type as stated in the comment.

2021-10-28 11:43 UTC, merged