Us 709 voltage level dialog
gridsuite/study-server pull request #158
Opened 2022-01-24 16:42 UTC by laurgarn

2022-01-25 09:40 UTC, FranckLecuyer requested changes

2022-01-25 09:40 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +        @RequestBody String createSubstationAttributes) {
createVoltageLevelAttributes

2022-01-25 09:40 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +            @ApiResponse(responseCode = "200", description = "The id of the network imported"),
keep previous indentations (this code has not been changed ...)
same remarks in following lines

2022-01-25 09:40 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +            @ApiResponse(responseCode = "200", description = "The id of the network imported"),
keep previous indentations

2022-01-25 09:40 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> +        // create substation
voltage level

2022-01-25 09:40 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> +        // create substation on modification node child of root node
voltage level

2022-01-25 11:32 UTC, laurgarn commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +        @RequestBody String createSubstationAttributes) {
done

2022-01-25 11:32 UTC, laurgarn commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +            @ApiResponse(responseCode = "200", description = "The id of the network imported"),
done

2022-01-25 11:33 UTC, laurgarn commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> +        // create substation
done

2022-01-25 11:33 UTC, laurgarn commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> +        // create substation on modification node child of root node
done

2022-01-26 14:54 UTC, FranckLecuyer approved these changes

2022-01-26 15:19 UTC, JacquesBorsenberger approved these changes

2022-01-27 09:38 UTC, merged