Us 936 allow to user export parameters from front
gridsuite/study-server pull request #205
Opened 2022-05-18 13:46 UTC by laurgarn

2022-05-25 08:11 UTC, JacquesBorsenberger approved these changes

2022-05-25 08:12 UTC, JacquesBorsenberger commented on src/main/java/org/gridsuite/study/server/StudyService.java
is this variable still used ?

2022-05-25 08:13 UTC, JacquesBorsenberger commented on src/main/java/org/gridsuite/study/server/StudyService.java
> +            .bodyToMono(String.class);
is this variable still used ? (typeRef)

2022-05-25 09:00 UTC, laurgarn commented on src/main/java/org/gridsuite/study/server/StudyService.java
> +            .bodyToMono(String.class);
Corrected :-)

2022-06-07 10:51 UTC, FranckLecuyer requested changes

2022-06-07 10:51 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> +        mockMvc.perform(get("/v1/studies/{studyUuid}/nodes/{nodeUuid}/export-network/{format}?formatParameters=%7B%22iidm.export.xml.indent%22%3Afalse%7D", studyNameUserIdUuid, rootNodeUuid, "XIIDM")
Maybe use URLEncoder.encode to pass the formatParameters json value ?

2022-06-07 12:43 UTC, FranckLecuyer approved these changes

2022-06-09 13:06 UTC, merged