add search by parentNode id to buses and busbar-sections
gridsuite/study-server pull request #232
Opened 2022-06-27 10:09 UTC by bendaamerahm

2022-06-27 11:59 UTC, FranckLecuyer approved these changes

2022-06-28 12:08 UTC, sBouzols requested changes

2022-06-29 10:49 UTC, sBouzols approved these changes

2022-06-29 10:49 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/StudyService.java
> +        UUID nodeUuidToSearchIn = nodeUuid;
doGetLastParentNodeBuilt check the current node status

2022-06-29 10:49 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/StudyService.java
> +        UUID nodeUuidToSearchIn = nodeUuid;
same same

2022-06-29 11:16 UTC, merged