[WIP] Add support for sensitivity analysis computation
gridsuite/study-server pull request #264
Opened 2022-08-11 14:15 UTC by FranckLecuyer

2022-09-06 14:56 UTC, niconoir reviewed
Minor remarks

2022-09-07 07:03 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/study/server/SensitivityAnalysisService.java
> +                               NetworkService networkStoreService,
Removed

2022-09-07 07:04 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +    public ResponseEntity<String> getsensitivityAnalysisStatus(@Parameter(description = "Study UUID") @PathVariable("studyUuid") UUID studyUuid,
Changed

2022-09-07 07:04 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +    public ResponseEntity<Void> stopsensitivityAnalysis(@Parameter(description = "Study uuid") @PathVariable("studyUuid") UUID studyUuid,
Changed

2022-09-07 13:22 UTC, niconoir approved these changes

2022-09-09 11:15 UTC, geofjamg requested changes
Same as for sensitivity analysis server, quad -> branch

2022-09-20 15:02 UTC, geofjamg approved these changes

2022-09-20 15:15 UTC, merged