Add the possibility to update an equipment deletion
gridsuite/study-server pull request #289
Opened 2022-10-21 09:41 UTC by flomillot

2022-10-21 13:33 UTC, FranckLecuyer requested changes

2022-10-21 13:33 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +        notificationService.emitStartModificationEquipmentNotification(studyUuid, nodeUuid, NotificationService.MODIFICATIONS_CREATING_IN_PROGRESS);
MODIFICATIONS_UPDATING_IN_PROGRESS

2022-10-21 16:10 UTC, flomillot commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +        notificationService.emitStartModificationEquipmentNotification(studyUuid, nodeUuid, NotificationService.MODIFICATIONS_CREATING_IN_PROGRESS);
Ah oui en effet, my bad, je change

2022-10-24 08:37 UTC, FranckLecuyer approved these changes

2022-10-24 12:39 UTC, bendaamerahm approved these changes

2022-10-25 13:20 UTC, niconoir approved these changes

2022-10-26 08:56 UTC, merged