remove study creation from case file
gridsuite/study-server pull request #291
Opened 2022-10-25 13:39 UTC by Walid-Sahnoun

Signed-off-by: walid-sahnoun <walid.sahnoun@rte-france.com>

2022-10-28 13:54 UTC, AbdelHedhili approved these changes

2022-11-10 15:12 UTC, SlimaneAmar requested changes

2022-11-10 15:12 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> +                        NOT_EXISTING_CASE_UUID, "false").header("userId", "userId"))
Do not modify indentation only because it makes it difficult to review

2022-11-10 15:12 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> -        UUID s2Uuid = createStudy("userId", TEST_FILE, IMPORTED_CASE_UUID_STRING, true);
Remove `createStudy` method

2022-11-14 08:17 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +
done

2022-11-14 08:17 UTC, Walid-Sahnoun commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> -        UUID s2Uuid = createStudy("userId", TEST_FILE, IMPORTED_CASE_UUID_STRING, true);
done

2022-11-14 08:17 UTC, Walid-Sahnoun commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> -    @Test
done

2022-11-14 16:11 UTC, SlimaneAmar approved these changes

2022-11-14 16:31 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/study/server/service/CaseService.java
>      public Boolean caseExists(UUID caseUuid) {
done

2022-11-15 16:05 UTC, merged