Moving a node around itself now throws an exception
gridsuite/study-server pull request #299
Opened 2022-11-17 13:13 UTC by archendel

Signed-off-by: LE SAULNIER Kevin <kevin.lesaulnier@rte-france.com>

2022-11-17 13:26 UTC, AbdelHedhili approved these changes

2022-11-17 13:28 UTC, AbdelHedhili requested changes
while you are at it add a test for this case

2022-11-18 09:12 UTC, AbdelHedhili approved these changes

2022-11-21 08:24 UTC, bendaamerahm approved these changes

2022-11-22 08:20 UTC, merged