[WIP] Refactor network modification endpoints
gridsuite/study-server pull request #302
Opened 2022-11-22 12:53 UTC by flomillot

2022-12-05 16:01 UTC, archendel commented on src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java
> +        if (cause instanceof TypeMismatchException && cause.getCause() != null && cause.getCause() != cause) {
should i be in the next handler ?

2022-12-06 11:14 UTC, flomillot commented on src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java
> +        if (cause instanceof TypeMismatchException && cause.getCause() != null && cause.getCause() != cause) {
Its the cause here, not the original exception. Did I miss something ?

2022-12-06 11:25 UTC, flomillot commented on src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java
> +        if (cause instanceof TypeMismatchException && cause.getCause() != null && cause.getCause() != cause) {
I don't understand ?

2022-12-06 11:25 UTC, flomillot commented on src/main/java/org/gridsuite/study/server/dto/modification/ModificationInfos.java
> -    private Set<String> substationIds = Set.of();
Same as for the other PR I guess, I put it back

2022-12-06 15:31 UTC, SlimaneAmar requested changes

2022-12-06 15:31 UTC, SlimaneAmar commented on pom.xml
> +        </dependency>
Add      
```
<dependency>
            <groupId>com.github.tomakehurst</groupId>
            <artifactId>wiremock</artifactId>
            <scope>test</scope>
        </dependency>
```

2022-12-06 15:31 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/study/server/NetworkModificationTest.java
> +            return "input-send";
Use static

2022-12-06 16:24 UTC, flomillot commented on src/test/java/org/gridsuite/study/server/NetworkModificationTest.java
> +            return "input-send";
Done

2022-12-07 08:18 UTC, archendel commented on src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java
> +        if (cause instanceof TypeMismatchException && cause.getCause() != null && cause.getCause() != cause) {
My mistake, indentation in git made me misread the original code 
All good then

2022-12-07 08:19 UTC, archendel commented on src/main/java/org/gridsuite/study/server/RestResponseEntityExceptionHandler.java
> +        if (cause instanceof TypeMismatchException && cause.getCause() != null && cause.getCause() != cause) {
my mistake, all good here

2022-12-07 08:21 UTC, archendel approved these changes
Test: OK
Code: OK

2022-12-07 13:36 UTC, SlimaneAmar requested changes

2022-12-07 13:36 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +                                                           @Parameter(description = "Network modification UUIDs") @PathVariable("modificationUuids") List<UUID> modificationUuids) {
I think the path variable does not work for a list

2022-12-07 16:05 UTC, SlimaneAmar requested changes

2022-12-07 16:05 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +                    .createModification(studyUuid, createModificationAttributes, groupUuid, modificationType, variantId, reportUuid, nodeInfos.getId().toString());
It's not `EquipmentModificationInfos`

2022-12-12 09:57 UTC, SlimaneAmar approved these changes

2022-12-12 10:05 UTC, merged