add useFeederPositionsparam as  new boolean param to sld (voltage-level) api
gridsuite/study-server pull request #305
Opened 2022-11-24 15:18 UTC by bendaamerahm

…el) api call

2022-11-25 08:21 UTC, geofjamg requested changes
Instead of useFeederPositions we should have an enum so that it could be extended to other kind of display easily: 
something like displayMode:
 - StateVariable
 - FeederPosition

2022-12-01 13:35 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +            ShortCircuitService shortCircuitService, CaseService caseService) {
undo

2022-12-01 13:55 UTC, etiennehomer requested changes

2022-12-01 13:55 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/StudyConstants.java
> +    public enum DisplayMode {
Maybe use a more specific name like SldLabellingMode ? SldDisplayMode?

2022-12-01 14:47 UTC, bendaamerahm commented on src/main/java/org/gridsuite/study/server/StudyConstants.java
> +    public enum DisplayMode {
i agree

2022-12-05 08:19 UTC, geofjamg approved these changes

2022-12-07 15:35 UTC, etiennehomer approved these changes

2022-12-15 16:22 UTC, merged