[wip] create load scaling
gridsuite/study-server pull request #323
Opened 2022-12-23 15:14 UTC by bendaamerahm

2023-01-06 10:22 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/study/server/NetworkModificationTest.java
> +        String loadScalingAttributes = "{\"type\":\"LOAD_SCALING\",\"variationType\":\"DELTA_P\",\"loadScalingVariations\":[{\"filters\":[{\"id\":\"b5c93a96-b325-47a6-8303-c6764ba680e5\",\"name\":\"f
Please do not use json hardcoded !
Use `createEquipmentModificationInfosBody`

2023-01-06 10:22 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/study/server/NetworkModificationTest.java
> +        String badBody = "{\"type\":\"" + ModificationType.LOAD_SCALING + "\",\"bogus\":\"bogus\"}";
Same

2023-01-09 12:28 UTC, FranckLecuyer requested changes

2023-01-13 14:22 UTC, FranckLecuyer approved these changes

2023-01-19 09:51 UTC, SlimaneAmar approved these changes

2023-01-19 11:24 UTC, merged