Api generic equipments
gridsuite/study-server pull request #343
Opened 2023-02-08 14:19 UTC by ElMehdiTailassan

2023-02-09 09:31 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +            equipmentsIds, equipmentsType);
would be better change name "equipmentsType" with "type" only ?

2023-02-13 12:21 UTC, SlimaneAmar commented
I think you should rebase your PR from [https://github.com/gridsuite/study-server/pull/338](https://github.com/gridsuite/study-server/pull/338)
The work has already done for equipmentsIds

2023-02-13 12:32 UTC, SlimaneAmar commented
You need modify tests ?

2023-02-13 12:34 UTC, SlimaneAmar commented
`equipmentType` and `equipmentPath` are not the same
See  [https://github.com/gridsuite/study-server/pull/338](https://github.com/gridsuite/study-server/pull/338)

2023-02-13 12:35 UTC, SlimaneAmar requested changes

2023-02-13 12:35 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +    @GetMapping(value = "/studies/{studyUuid}/nodes/{nodeUuid}/network-map/{equipmentType}/{equipmentId}")
Use a RequestParam for equipmentType like :
[https://github.com/gridsuite/study-server/pull/338](https://github.com/gridsuite/study-server/pull/338)

2023-02-13 12:35 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +    @GetMapping(value = "/studies/{studyUuid}/nodes/{nodeUuid}/network-map/{equipmentType}")
/studies/{studyUuid}/nodes/{nodeUuid}/network-map/equipments?equipmentType=value

2023-02-13 12:35 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +                                      boolean inUpstreamBuiltParentNode, String equipmentType) {
`equipmentType` and `equipmentPath` are not the same

2023-06-05 14:54 UTC, closed without merging