Add a new endpoint to get the nominal voltages
gridsuite/study-server pull request #349
Opened 2023-02-17 17:14 UTC by flomillot

2023-02-21 08:05 UTC, SlimaneAmar requested changes

2023-02-21 09:47 UTC, flomillot commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +        List<VoltageLevelMapData> voltageLevelsMapData = networkMapService.getVoltageLevelMapData(networkUuid, variantId);
I though map-server is about to disappear ?

2023-02-22 13:30 UTC, SlimaneAmar approved these changes

2023-02-23 12:36 UTC, SlimaneAmar approved these changes

2023-04-19 07:07 UTC, jonenst commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +        List<VoltageLevelMapData> voltageLevelsMapData = networkMapService.getVoltageLevelMapData(networkUuid, variantId);
maybe just add a todo ? And maybe this can be added all the way to the networkstore and even iidm api ?

2023-04-19 07:10 UTC, SlimaneAmar approved these changes

2023-04-19 12:36 UTC, flomillot commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +        List<VoltageLevelMapData> voltageLevelsMapData = networkMapService.getVoltageLevelMapData(networkUuid, variantId);
What is to do exactly ? Adding it in map-server or network store / iidm ? If it's just map-server I can do it now, for the others indeed I don't know these services

2023-04-27 15:25 UTC, merged