more detailled node update notif
gridsuite/study-server pull request #362
Opened 2023-03-23 11:38 UTC by AbdelHedhili

2023-03-24 14:56 UTC, SlimaneAmar commented
I think it would be better to differentiate between renaming and updating with a separate endpoint
This would greatly simplify the code.

2023-03-24 14:56 UTC, SlimaneAmar requested changes

2023-04-03 08:16 UTC, Walid-Sahnoun approved these changes

2023-04-03 08:58 UTC, jonenst commented on src/main/java/org/gridsuite/study/server/service/NetworkModificationTreeService.java
> +    private boolean isRenameNode(AbstractNode node) {
should add a comment here to explain the rationale behind this code

2023-04-03 09:46 UTC, SlimaneAmar approved these changes

2023-04-04 11:15 UTC, jonenst approved these changes

2023-04-04 11:39 UTC, merged