draft version of creation sensiParam db
gridsuite/study-server pull request #427
Opened 2023-08-29 07:55 UTC by ghazwarhili

2023-09-11 16:28 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/study/server/service/SensitivityAnalysisService.java
> +import org.gridsuite.study.server.dto.sensianalysis.*;
no need to this change

2023-09-11 16:28 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/study/server/service/SensitivityAnalysisService.java
> +import org.gridsuite.study.server.repository.*;
no need to this change

2023-09-11 16:28 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/study/server/service/SensitivityAnalysisService.java
> +import java.util.*;
no need to this change

2023-09-12 12:51 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/study/server/dto/SensitivityAnalysisInputData.java
> +import org.gridsuite.study.server.repository.*;
import class by class (not with *)

2023-09-12 12:53 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/IdentifiableAttributes.java
> +import lombok.*;
also here (not with *)

2023-09-12 12:53 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/FilterEquipments.java
> +import lombok.*;
also here

2023-09-12 13:07 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/FilterEquipments.java
> +
add author copyright

2023-09-12 13:22 UTC, Walid-Sahnoun commented on src/test/java/org/gridsuite/study/server/SensitivityAnalysisTest.java
> +import java.util.*;
no need to this change

2023-09-12 19:23 UTC, ghazwarhili commented on src/main/java/org/gridsuite/study/server/service/SensitivityAnalysisService.java
> +import org.gridsuite.study.server.dto.sensianalysis.*;
yes

2023-09-13 07:05 UTC, ghazwarhili commented on src/test/java/org/gridsuite/study/server/SensitivityAnalysisTest.java
> +import java.util.*;
done

2023-09-13 07:05 UTC, ghazwarhili commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/FilterEquipments.java
> +
done

2023-09-13 07:05 UTC, ghazwarhili commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/SensitivityAnalysisParametersInfos.java
> +import lombok.*;
done

2023-09-13 07:05 UTC, ghazwarhili commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/FilterEquipments.java
> +import lombok.*;
done

2023-09-13 07:05 UTC, ghazwarhili commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/IdentifiableAttributes.java
> +import lombok.*;
done

2023-09-13 07:05 UTC, ghazwarhili commented on src/main/java/org/gridsuite/study/server/dto/SensitivityAnalysisInputData.java
> +import org.gridsuite.study.server.repository.*;
done

2023-09-13 07:06 UTC, ghazwarhili commented on src/main/java/org/gridsuite/study/server/service/SensitivityAnalysisService.java
> +import java.util.*;
done

2023-09-13 07:06 UTC, ghazwarhili commented on src/main/java/org/gridsuite/study/server/service/SensitivityAnalysisService.java
> +import org.gridsuite.study.server.repository.*;
done

2023-09-13 07:23 UTC, YenguiSeddik approved these changes

2023-09-13 09:07 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +                                                       @RequestHeader(HEADER_USER_ID) String userId) {
The userId is not used for the sensitivity computation

2023-09-13 09:30 UTC, etiennehomer requested changes

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +                                                       @RequestHeader(HEADER_USER_ID) String userId) {
The userId is not used for the sensitivity computation. You can remove it

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/dto/SensitivityAnalysisInputData.java
> +    private List<SensitivityParametersInjectionsSetEntity> sensitivityInjectionsSets;
You should use the DTO you created

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/IdentifiableAttributes.java
> +
Author

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/SensitivityAnalysisHvdcParameterInfos.java
> +
Author

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/SensitivityAnalysisInjectionsParameterInfos.java
> +
Author

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/SensitivityAnalysisNodesParameterInfos.java
> +
Author

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/SensitivityAnalysisPtsParameterInfos.java
> +
Author

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/repository/FilterEquipmentsEmbeddable.java
> + * @author Hugo Marcellin <hugo.marcelin at rte-france.com>
Author

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/repository/SensitivityParametersEntity.java
> + * @author SAHNOUN Walid <walid.sahnoun@rte-france.com>
Author

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/repository/SensitivityParametersInjectionsEntity.java
> +
Author

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/repository/SensitivityParametersInjectionsSetEntity.java
> +
Author

2023-09-13 09:30 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/repository/SensitivityParametersPstEntity.java
> +
Author

2023-09-13 11:43 UTC, etiennehomer requested changes

2023-09-13 11:43 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/repository/SensitivityParametersEntity.java
> +public class SensitivityParametersEntity {
You should keep SensitivityAnalysisParametersEntity to be homogeneous

2023-09-13 11:43 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/repository/SensitivityParametersEntity.java
> +package org.gridsuite.study.server.repository;
You should create a sensitivity package in repository to group all the sensi entities

2023-09-13 11:51 UTC, etiennehomer requested changes

2023-09-13 11:51 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/SensitivityAnalysisHvdcParameterInfos.java
> +    List<FilterEquipments> monitoredBranches;
Those 3 fields are present in SensitivityAnalysisInjectionsParameterInfos, SensitivityAnalysisHvdcParameterInfos, SensitivityAnalysisPtsParameterInfos, SensitivityAnalysisNodesParameterInfos. 
You could do a class of it. 

And same for entities. You create several tables that have the same structure. There might be something simpler to be done

2023-09-15 13:59 UTC, jonenst commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/SensitivityAnalysisInputData.java
> +        public SensitivityInjectionsSet(List<FilterEquipments> monitoredBranches,
use allArgsConstructor ?

2023-09-15 14:07 UTC, jonenst commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/SensitivityAnalysisInputData.java
> +    public static class Ident {
Not used anymore because replaced by FilterEquipments ? To delete ?

2023-09-18 09:02 UTC, FranckLecuyer requested changes

2023-09-19 11:14 UTC, FranckLecuyer approved these changes

2023-09-19 12:29 UTC, EstherDarkish commented on src/main/java/org/gridsuite/study/server/repository/ContainerEquipmentsEmbeddable.java
> +    public static List<ContainerEquipmentsEmbeddable> toEmbeddableFilterEquipments(List<EquipmentsContainer> containers) {
Should be renamed ?

2023-09-19 12:29 UTC, EstherDarkish commented on src/main/java/org/gridsuite/study/server/repository/ContainerEquipmentsEmbeddable.java
> +    public static List<EquipmentsContainer> fromEmbeddableFilterEquipments(List<ContainerEquipmentsEmbeddable> containers) {
Should be renamed ?

2023-09-19 12:36 UTC, etiennehomer requested changes

2023-09-20 15:09 UTC, etiennehomer requested changes

2023-09-20 15:09 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/dto/sensianalysis/EquipmentsContainer.java
> +    @Schema(description = "equipments in container")
You should remove identifiableAttributes and  notFoundEquipments, you don't use it

2023-09-26 17:50 UTC, etiennehomer requested changes

2023-09-26 17:50 UTC, etiennehomer commented on src/main/java/org/gridsuite/study/server/repository/sensianalysis/SensitivityAnalysisParametersEntity.java
> + * @author SAHNOUN Walid <walid.sahnoun@rte-france.com>
Ghazwa

2023-09-26 17:50 UTC, etiennehomer commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +
to remove

2023-09-26 17:50 UTC, etiennehomer commented on src/main/resources/db/changelog/changesets/changelog_20230920T153947Z.xml
> +<?xml version="1.1" encoding="UTF-8" standalone="no"?>
this file is to remove ?

2023-09-26 17:50 UTC, etiennehomer commented on src/main/resources/application-local.yml
> +  jpa:
To clean up

2023-09-27 18:53 UTC, EstherDarkish approved these changes

2023-09-28 17:21 UTC, etiennehomer approved these changes

2023-09-29 09:00 UTC, merged