Reindex study at start
gridsuite/study-server pull request #432
Opened 2023-09-06 14:41 UTC by sBouzols

2023-09-14 14:09 UTC, FranckLecuyer requested changes

2023-09-14 14:09 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +            reindexStudy(duplicatedStudy.getId());
Why this change ?

2023-09-18 13:25 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/dto/StudyIndexationStatus.java
> +    INDEX_DONE
I just used the status defined in the ticket. It seems correct. Will ask to @SlimaneAmar and let's go

2023-09-18 13:25 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/notification/NotificationService.java
> +        sendUpdateMessage(MessageBuilder.withPayload(status.toString())
right ! I will remove this !

2023-09-18 14:53 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/dto/StudyIndexationStatus.java
> +    INDEX_DONE
INDEXED

2023-09-18 15:13 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +            reindexStudy(duplicatedStudy.getId());
reverted

2023-09-19 08:55 UTC, FranckLecuyer approved these changes

2023-09-21 13:38 UTC, SlimaneAmar requested changes

2023-09-21 13:41 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/notification/NotificationService.java
> +    public void emitStudyChanged(UUID studyUuid, String updateType, StudyIndexationStatus status) {
@PostCompletion
    public void emitStudyIndexationStatusChanged(UUID studyUuid, StudyIndexationStatus status) {
        sendUpdateMessage(MessageBuilder.withPayload("")
                .setHeader(HEADER_STUDY_UUID, studyUuid)
                .setHeader(HEADER_UPDATE_TYPE, NotificationService.UPDATE_TYPE_INDEXATION_STATUS)
                .setHeader(HEADER_INDEXATION_STATUS, status.name())
                .build());
    }

2023-09-21 15:23 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +        } catch (HttpStatusCodeException e) {
I tried something, could you check if it's ok for you ?

2023-09-21 15:24 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/repository/StudyEntity.java
> +    @Column(name = "indexationStatus", length = 32, columnDefinition = "varchar(32) default 'NOT_INDEXED'")
Ok changed by @Builder.Default and java initialization but it's not a default value in BDD, and it will accept null then.

2023-09-21 15:25 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
>          } catch (HttpStatusCodeException e) {
Could you check if it's ok for you ?

2023-09-26 06:34 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/service/NetworkConversionService.java
> +                throw new StudyException(NETWORK_NOT_FOUND);
Why ?
NetworkConversionServer never return 404 ?

2023-09-26 06:34 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +    private StudyIndexationStatus getStudyIndexationStatus(StudyEntity study) {
Remove all unnecessary private methods
```
    public StudyIndexationStatus getStudyIndexationStatus(UUID studyUuid) {
        StudyEntity study = studyRepository.findById(studyUuid).orElseThrow(() -> new StudyException(STUDY_NOT_FOUND));
        if (study.getIndexationStatus() == StudyIndexationStatus.INDEXED
            && !networkConversionService.checkStudyIndexationStatus(study.getNetworkUuid())) {
            updateStudyIndexationStatus(study, StudyIndexationStatus.NOT_INDEXED);
        }
        return study.getIndexationStatus();
    }
```

2023-09-28 13:56 UTC, SlimaneAmar approved these changes

2023-10-02 12:57 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +    private StudyIndexationStatus getStudyIndexationStatus(StudyEntity study) {
fixed

2023-10-02 13:11 UTC, merged