set inUpstreamBuiltParentNode to false by default for get equipement …
gridsuite/study-server pull request #446
Opened 2023-10-02 22:19 UTC by jamal-khey

…APIs

2023-10-10 13:33 UTC, SlimaneAmar approved these changes

2023-10-17 13:20 UTC, FranckLecuyer approved these changes

2023-10-17 13:23 UTC, antoinebhs requested changes
There are some API calls that rely on the inUpstreamBuildParentNode set to true. We should check carefully each call and decide whether or not inUpstreamBuildParentNode should be set to true. 
With the changes, I have an internal error 500 when I try to delete an HVDC line on a node that is not built. I have no issues when I'm on the main branch. See Antoine/test/recollement on dev-OPF as an example. I think there are other calls that might be problematic. I only tested https://github.com/gridsuite/gridstudy-app/blob/c77dadb572feb8d092981851de3fc4b001498226/src/services/study/network-map.js#L22.

2023-10-17 15:26 UTC, jamal-khey commented
> There are some API calls that rely on the inUpstreamBuildParentNode set to true. We should check carefully each call and decide whether or not inUpstreamBuildParentNode should be set to true. With the changes, I have an internal error 500 when I try to delete an HVDC line on a node that is not built. I have no issues when I'm on the main branch. See Antoine/test/recollement on dev-OPF as an example. I think there are other calls that might be problematic. I only tested https://github.com/gridsuite/gridstudy-app/blob/c77dadb572feb8d092981851de3fc4b001498226/src/services/study/network-map.js#L22.

after a discution with Christelle , it has been decided to keep this parameter to true for the end point.

2023-11-08 08:12 UTC, antoinebhs approved these changes

2023-11-08 14:36 UTC, merged