merge check indexation status and reindex all in one endpoint
gridsuite/study-server pull request #448
Opened 2023-10-04 16:09 UTC by achour94

2023-10-13 08:11 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +@SuppressWarnings("checkstyle:RegexpSingleline")
Why this suppressWarnings ?

2023-10-13 08:14 UTC, sBouzols commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +        StudyIndexationStatus status = getStudyIndexationStatus(studyUuid);
Maybe `getStudyIndexationStatus` doesn't need to be @Transactional ?

2023-10-13 08:14 UTC, sBouzols requested changes
Add some TU otherwise you have 0% coverage

2023-10-17 15:13 UTC, sBouzols approved these changes
Code Review OK
Tests OK (standard, with study-server stopped, with conversion-server stopped)

2023-10-18 09:36 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +        StudyIndexationStatus status = getStudyIndexationStatus(studyUuid);
Make private `getStudyIndexationStatus`

2023-10-18 09:36 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +    @PostMapping(value = "/studies/{studyUuid}/reindex-if-needed")
I think it might be better to keep the endpoint `reindex-all` to force reindexation ?
/studies/{studyUuid}/reindex-all?if-needed=true/false

2026-07-07 12:41 UTC, closed without merging