Restore and Delete Node can be done with multiple ids in one call
gridsuite/study-server pull request #485
Opened 2023-11-30 12:43 UTC by lilian-houdelet

2023-12-01 09:37 UTC, AbdelHedhili requested changes

2023-12-01 09:37 UTC, AbdelHedhili commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +                                           @Parameter(description = "id of child to remove") @RequestParam("ids") List<UUID> nodeIds,
update description

2023-12-01 09:55 UTC, lilian-houdelet commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +                LOGGER.trace("Delete node '{}' of study '{}' : {} seconds", nodeId.toString().replaceAll("[\n\r]", "_"), studyUuid,
I have issue with the log and sonar

2023-12-01 09:56 UTC, AbdelHedhili commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +                LOGGER.trace("Delete node '{}' of study '{}' : {} seconds", nodeId.toString().replaceAll("[\n\r]", "_"), studyUuid,
what issue ?

2023-12-01 15:23 UTC, lilian-houdelet commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +                LOGGER.trace("Delete node '{}' of study '{}' : {} seconds", nodeId.toString().replaceAll("[\n\r]", "_"), studyUuid,
don't remember very well, but was about security and I think it was talking about injection,

2023-12-15 08:18 UTC, souissimai approved these changes
it seems good(code and test)

2023-12-18 11:09 UTC, merged