Add endpoint to unbuild node
gridsuite/study-server pull request #488
Opened 2023-12-04 12:11 UTC by klesaulnier

2023-12-06 12:27 UTC, AbdelHedhili requested changes

2023-12-06 12:27 UTC, AbdelHedhili commented on src/test/java/org/gridsuite/study/server/NetworkModificationUnitTest.java
> +package org.gridsuite.study.server;
copyrights and author

2023-12-06 12:27 UTC, AbdelHedhili commented on src/test/java/org/gridsuite/study/server/NetworkModificationUnitTest.java
> +        assertEquals(BuildStatus.NOT_BUILT, node3Infos.getNodeBuildStatus().getLocalBuildStatus());
It would be a bit cleaner to use orElseThrow here instead of letting it get a nullPointer after in the case the nodes are not found no ?

2023-12-06 13:56 UTC, klesaulnier commented on src/test/java/org/gridsuite/study/server/NetworkModificationUnitTest.java
> +package org.gridsuite.study.server;
fixed

2023-12-06 14:02 UTC, klesaulnier commented on src/test/java/org/gridsuite/study/server/NetworkModificationUnitTest.java
> +}
fixed

2023-12-07 09:14 UTC, AbdelHedhili approved these changes

2023-12-07 10:33 UTC, Meklo approved these changes

2023-12-14 08:59 UTC, merged