Switch study public/private
gridsuite/study-server pull request #50
Opened 2020-10-16 22:46 UTC by AbdelHedhili

2020-10-19 10:56 UTC, geofjamg requested changes

2020-10-19 10:56 UTC, geofjamg commented on src/main/java/org/gridsuite/study/server/StudyService.java
> +                        studyEntity.isCasePrivate(), new LoadFlowResult(studyEntity.getLoadFlowResult().getStatus()), studyEntity.getLoadFlowParameters());
We loose security analysis result UUID

2020-10-19 10:56 UTC, geofjamg commented on src/main/java/org/gridsuite/study/server/StudyService.java
> +                insert = studyRepository.insertStudy(studyEntity.getStudyName(), userId, false, studyEntity.getNetworkUuid(),
Same

2020-10-19 10:56 UTC, geofjamg commented on src/main/java/org/gridsuite/study/server/dto/StudyInfos.java
> +    Boolean isPrivate;
boolean ?

2020-10-19 10:56 UTC, geofjamg commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> +                    && source.getIsPrivate().equals(s.getIsPrivate());
== if boolean?

2020-10-19 11:15 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/StudyService.java
> +
Maybe a more concise form?
         return getStudy (studyName, userId) .switchIfEmpty (Mono.error (new StudyException (STUDY_NOT_FOUND))). flatMap (studyEntity ->
             (studyEntity.isPrivate () == toPrivate)? Mono.just (studyEntity):
                     studyRepository.deleteStudy (userId, studyName)
                     .then (insertStudy (studyEntity.getStudyName (), userId, toPrivate, studyEntity.getNetworkUuid (),
                             studyEntity.getNetworkId (), studyEntity.getDescription (), studyEntity.getCaseFormat (), studyEntity.getCaseUuid (),
                             studyEntity.isCasePrivate (), new LoadFlowResult (studyEntity.getLoadFlowResult (). getStatus ()), studyEntity.getLoadFlowParameters ()))
         ) .map (StudyService :: toInfos);

2020-10-19 11:25 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> +
Missing the non-existent study case test ?

2020-10-19 13:32 UTC, SlimaneAmar approved these changes

2020-10-20 16:26 UTC, geofjamg approved these changes

2020-10-20 16:26 UTC, merged