[WIP] Export security-analysis results
gridsuite/study-server pull request #504
Opened 2024-01-08 10:22 UTC by klesaulnier

2024-01-12 10:37 UTC, Meklo approved these changes

2024-01-17 08:45 UTC, Tristan-WorkGH requested changes

2024-01-17 08:45 UTC, Tristan-WorkGH commented on src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java
> +                && r.getBody().equals(CSV_TRANSLATION_DTO_STRING)
```suggestion
                && CSV_TRANSLATION_DTO_STRING.equals(r.getBody())
```

2024-01-17 08:45 UTC, Tristan-WorkGH commented on src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java
> +                && r.getBody().equals(CSV_TRANSLATION_DTO_STRING)
```suggestion
                && CSV_TRANSLATION_DTO_STRING.equals(r.getBody())
```

2024-01-17 08:45 UTC, Tristan-WorkGH commented on src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java
> +                && r.getBody().equals(CSV_TRANSLATION_DTO_STRING)
```suggestion
                && CSV_TRANSLATION_DTO_STRING.equals(r.getBody())
```

2024-01-17 08:45 UTC, Tristan-WorkGH commented on src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java
> +                && r.getBody().equals(CSV_TRANSLATION_DTO_STRING)
```suggestion
                && CSV_TRANSLATION_DTO_STRING.equals(r.getBody())
```

2024-01-17 13:36 UTC, klesaulnier commented on src/main/java/org/gridsuite/study/server/StudyController.java
> +                                                                           @Parameter(description = "Csv translation") @RequestBody String csvTranslations) {
fixed

2024-01-17 13:40 UTC, Tristan-WorkGH commented on src/main/java/org/gridsuite/study/server/service/SecurityAnalysisService.java
>              .queryParam("size", pageable.getPageSize());
ah no ... nothing doing it for us

2024-01-17 13:45 UTC, klesaulnier commented on src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java
> +                        .addHeader("Content-Type", "application/json; charset=utf-8");
fixed in the whole file

2024-01-17 13:45 UTC, klesaulnier commented on src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java
> +                        .addHeader("Content-Type", "application/json; charset=utf-8");
same

2024-01-17 13:45 UTC, klesaulnier commented on src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java
> +                        .addHeader("Content-Type", "application/json; charset=utf-8");
same

2024-01-17 13:47 UTC, klesaulnier commented on src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java
> +                && r.getBody().equals(CSV_TRANSLATION_DTO_STRING)
fixed

2024-01-17 13:47 UTC, klesaulnier commented on src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java
> +                && r.getBody().equals(CSV_TRANSLATION_DTO_STRING)
fixed

2024-01-17 13:47 UTC, klesaulnier commented on src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java
> +                && r.getBody().equals(CSV_TRANSLATION_DTO_STRING)
fixed

2024-01-17 13:47 UTC, klesaulnier commented on src/test/java/org/gridsuite/study/server/SecurityAnalysisTest.java
> +                && r.getBody().equals(CSV_TRANSLATION_DTO_STRING)
fixed

2024-01-17 14:04 UTC, Tristan-WorkGH approved these changes

2024-01-22 08:19 UTC, merged