Dynamic Simulation - Exception when running simulation without curves
gridsuite/study-server pull request #514
Opened 2024-01-17 22:39 UTC by thangqp

2024-01-19 13:03 UTC, TheMaskedTurtle requested changes

2024-01-19 15:28 UTC, flomillot approved these changes

2024-01-19 16:41 UTC, thangqp commented on src/main/java/org/gridsuite/study/server/service/dynamicsimulation/impl/DynamicSimulationServiceImpl.java
> +        List<TimeSeries<?, ?>> timeSeries = new ArrayList<>();
It is for just satisfy Sonar!

2024-01-19 16:50 UTC, flomillot commented on src/main/java/org/gridsuite/study/server/service/dynamicsimulation/impl/DynamicSimulationServiceImpl.java
> +        List<TimeSeries<?, ?>> timeSeries = new ArrayList<>();
Ah ok...

2024-01-19 17:12 UTC, thangqp commented on src/main/java/org/gridsuite/study/server/service/dynamicsimulation/impl/DynamicSimulationServiceImpl.java
> +        return resultUuidOpt.map(dynamicSimulationClient::getStatus).orElse(null);
DONE

2024-01-19 17:12 UTC, thangqp commented on src/main/java/org/gridsuite/study/server/service/dynamicsimulation/impl/DynamicSimulationServiceImpl.java
> +                metadataList = timeSeriesClient.getTimeSeriesGroupMetadata(timeSeriesUuid)
DONE! Add check null and check empty list

2024-01-19 17:13 UTC, thangqp commented on src/main/java/org/gridsuite/study/server/service/dynamicsimulation/impl/DynamicSimulationServiceImpl.java
> +                timeSeries = (List) timeSeriesClient.getTimeSeriesGroup(timeSeriesUuid, timeSeriesNames);
DONE! In the TimeSeriesClientImpl#getTimeSeriesGroup, add check null for json and return a empty list otherwise

2024-01-19 17:14 UTC, thangqp commented on src/main/java/org/gridsuite/study/server/service/dynamicsimulation/impl/DynamicSimulationServiceImpl.java
> +        List<TimeSeries<?, ?>> timeSeries = new ArrayList<>();
Anyway, I did revert to the original code..

2024-01-22 09:00 UTC, TheMaskedTurtle approved these changes

2024-01-22 10:31 UTC, merged