Move loadflow provider to loadflow-server
gridsuite/study-server pull request #527
Opened 2024-02-08 08:25 UTC by ayolab

2024-02-12 12:59 UTC, ayolab commented on src/main/java/org/gridsuite/study/server/RestTemplateConfig.java
> +        final RestTemplate restTemplate = new RestTemplate(new HttpComponentsClientHttpRequestFactory());
the Apache HttpComponents dependency was missing, Fixed

2024-02-12 13:18 UTC, SlimaneAmar commented on pom.xml
> +            <version>5.3</version>
Move version in a property and use it in the dependencyManagement

2024-02-12 15:17 UTC, dbraquart requested changes
code: only a remark
tests: ok

2024-02-14 15:13 UTC, dbraquart approved these changes
code: ok
tests: ok

2024-02-22 16:31 UTC, SlimaneAmar approved these changes

2024-02-23 14:22 UTC, merged