Feature: make getDefaultLoadFlowProvider return provider from profile when available
gridsuite/study-server pull request #564
Opened 2024-05-14 20:26 UTC by jonenst

2024-05-17 12:20 UTC, ayolab approved these changes

2024-05-17 16:48 UTC, dbraquart requested changes
code: ok, just a comment to remove
tests: ko, not conform
- "Reset All" button : works as expected
- "Reset provider default values":
  - with no profile : ok
  - with a profile: ko. we still restore all params stored in the profile, while we should set the provider dft values (to be confirmed with the PO ?)

2024-05-17 16:48 UTC, dbraquart commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +                    // in case of duplication error (ex: wrong/dangling uuid in the profile), move on with default params below
remove comment

2024-05-17 16:48 UTC, dbraquart commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +                    LOGGER.error(String.format("Could not get loadflow parameters with id '%s' from user/profile '%s/%s'. Using default parameters",
```suggestion
                    LOGGER.error(String.format("Could not get loadflow parameters with id '%s' from user/profile '%s/%s'. Using default provider",
```

2024-05-21 09:10 UTC, dbraquart approved these changes
code: ok
tests: ok

2024-05-21 09:56 UTC, merged