add security-analysis/invalidate-status endpoint
gridsuite/study-server pull request #604
Opened 2024-08-22 15:02 UTC by jamal-khey

2024-09-10 10:02 UTC, sBouzols requested changes

2024-09-10 10:39 UTC, jamal-khey commented on src/main/java/org/gridsuite/study/server/service/StudyService.java
> +        invalidateSecurityAnalysisStatusOnAllNodes(studyUuid);
done

2024-09-10 13:28 UTC, sBouzols approved these changes
Code Review OK

2024-09-11 13:07 UTC, souissimai approved these changes
test ok code ok

2024-09-11 13:16 UTC, merged