Fix matcher study infos [WIP]
gridsuite/study-server pull request #72
Opened 2021-03-24 10:51 UTC by ChamseddineBhd

2021-03-29 15:02 UTC, SlimaneAmar requested changes

2021-03-29 15:02 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/study/server/StudyTest.java
> +                .value(studies -> assertTrue("response should match", new MatcherCreatedStudyBasicInfos<CreatedStudyBasicInfos>(CreatedStudyBasicInfos.builder().studyName("studyName").userId("userId"
Why `assertTrue` ?
We just need to pass a matcher to the value method of `WebTestClient`

2021-04-07 11:00 UTC, SlimaneAmar approved these changes

2021-04-08 07:36 UTC, jonenst approved these changes

2021-04-08 07:37 UTC, merged