integration with report server
gridsuite/study-server pull request #94
Opened 2021-06-09 16:02 UTC by JacquesBorsenberger

Signed-off-by: jacqbors <jacques.borsenberger@rte-france.com>

2021-06-09 16:26 UTC, SlimaneAmar requested changes

2021-06-09 16:26 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/study/server/StudyService.java
> +            .onStatus(httpStatus -> httpStatus == HttpStatus.NOT_FOUND, r -> Mono.empty()) // Ignore because modification group does not exist if no modifications
Change the comment by no report

2021-06-09 16:43 UTC, SlimaneAmar commented
Need to add  in the application.yml :
```
report-server:
    base-uri: http://localhost:5028
```

2021-07-02 14:33 UTC, jonenst approved these changes

2021-07-02 14:33 UTC, merged